// <auto-generated />
namespace WhereToPlay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2AddPasswordSalt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2AddPasswordSalt));
        
        string IMigrationMetadata.Id
        {
            get { return "201601160854565_2AddPasswordSalt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
